# Generated by Django 5.2.4 on 2025-07-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(choices=[('QR', 'Qr'), ('CREDIT', 'Credit')], default='QR', max_length=10),
        ),
    ]
