# Generated by Django 5.2.4 on 2025-07-15 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_paymentmethod_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='remaining_amout',
            new_name='remaining_amount',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shop.orderitem'),
        ),
    ]
