# Generated by Django 5.2.4 on 2025-07-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_remaining_amout_product_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
